#!/bin/bash -l
#PBS -l mem=32gb
#PBS -l walltime=24:00:00
#PBS -o Output.job
#PBS -j oe
#PBS -l nodes=1:ppn=20
#PBS -M jakub.krajniak@cs.kuleuven.be
#PBS -A lp_sim_interpoco
#PBS -N dacron_water

source switch_to_2015a
module purge

cd $PBS_O_WORKDIR

module load 2015a/h5py
module load 2015a/espressopp/chem_devel
module load chemlab/dev
# Set up OpenMPI environment
n_proc=$(cat $PBS_NODEFILE | wc -l)
n_node=$(cat $PBS_NODEFILE | uniq | wc -l)
#mpdboot -f $PBS_NODEFILE -n $n_node -r ssh -v

#for rr in 0.0005 0.001 0.01 0.1 0.5 1.0; do
for rr in 0.0001; do
    rng="`shuf -i 12345-99999 -n1`"
    sed -e "s/RATE/$rr/g" reaction.tpl > reaction_${rr}.cfg
    mpirun -n 18 start_simulation.py @params --rng_seed ${rng} --output_prefix "data/r_${rr}_0.01_1000_0.48_0.44" --reactions reaction_${rr}.cfg &> run_${rng}_${rr}.log
done
