#!/bin/bash -l
#PBS -l mem=32gb
#PBS -l walltime=24:00:00
#PBS -o Output.job
#PBS -j oe
#PBS -l nodes=1:ppn=20
#PBS -M jakub.krajniak@cs.kuleuven.be
#PBS -A lp_sim_interpoco

module purge

cd $PBS_O_WORKDIR

module load h5py

for h5 in *.h5; do
    nohup python ../../../analysis_code/get_polstat.py $h5 &
    nohup python ../../../analysis_code/get_cr.py $h5 &
done

for p in `jobs -p`; do
    wait $p;
done
